name: CI-CD

on:
  push:
    branches: ["main"]
  workflow_dispatch: 
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Autenticar no Docker Hub
        run: echo "Executando comando Docker login"
      - name: Construção da imagem docker
        run: echo "Construindo imagem docker"
      - name: Enviar imagem docker
        run: echo "Executando comando Docker push"
  cd:
    runs-on: ubuntu-latest
    steps:
      - name: Autenticar na AWS
        run: echo "Executando comando aws configure"
      - name: Construção o kubectl
        run: echo "Executando o comando aws eks update-kubeconfig"
      - name: Aplicar os manifestos no kubernetes
        run: echo "Executando comando kubectl apply"
